### ISSUE TITLE
search beyond 5 locations

### ISSUE THREAD

**Issue by aa755** [sjsinghai/usps-passport-appointment-locator#1]
is there an easy way to search beyond 5 closest locations. I increased radius to 100 miles and it still seems to search only 5 closest locations.  
If there isn't, I'd probably find the nearby zip code, find 5 closest locations of all of them, de-duplicate and then search for appointments.

**Comment by sjsinghai** [comment]
Yes I noticed the same. The USPS's API call doesn't seem to honor the search radius. What you suggest is a good way to improve the existing behavior.

**Comment by aa755** [comment]
A dirty implementation of it is in https://github.com/aa755/usps-passport-appointment-locator 
feel free to merge the changes to this repo.
